insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC1','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC2','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC3','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC4','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC5','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC6','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC7','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC8','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC9','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC10','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC11','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC12','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC13','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC14','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC15','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC16','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC17','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC18','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC19','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC20','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC21','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC22','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC23','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC24','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC25','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC26','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC27','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC28','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC29','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC30','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC31','2021-02-04','P');
insert into tblCompleteStatus(completeStatusSeq,classRegSeq,completeStatusDate,completeStatusPF) values (seqCompleteStatus.nextVal,'SC32','2021-02-04','P');


commit;
