insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S108','CCNA','2016-02-23');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S145','CCNA','2012-12-16');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S103','정보처리산업기사','2014-03-18');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S172','컴퓨터활용능력 2급','2018-03-19');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S130','CCNA','2015-04-13');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S10','컴퓨터활용능력 2급','2018-04-15');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S4','정보처리 기능사','2013-06-02');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S165','컴퓨터활용능력 2급','2014-04-15');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S13','정보처리산업기사','2015-07-31');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S111','리눅스 마스터','2017-02-08');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S10','정보처리 기능사','2013-08-02');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S55','정보처리기사','2018-02-14');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S69','네트워크관리사 2급','2019-05-02');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S117','CCNA','2017-01-04');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S74','정보처리기사','2012-04-16');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S188','컴퓨터활용능력 2급','2018-09-22');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S144','네트워크관리사 2급','2018-07-30');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S119','정보처리 기능사','2019-07-06');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S85','리눅스 마스터','2012-04-13');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S123','리눅스 마스터','2017-11-03');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S159','CCNA','2012-02-13');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S103','CCNA','2011-01-08');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S161','정보처리기사','2018-01-06');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S65','컴퓨터활용능력 2급','2011-10-29');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S69','ITQ','2014-10-31');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S32','정보처리기사','2018-06-01');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S115','CCNA','2017-08-20');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S184','네트워크관리사 2급','2010-03-14');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S150','리눅스 마스터','2015-09-30');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S161','ITQ','2011-03-23');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S49','CCNA','2010-08-20');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S21','정보처리 기능사','2015-02-13');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S64','정보처리기사','2017-03-03');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S163','리눅스 마스터','2012-08-07');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S79','네트워크관리사 2급','2019-09-26');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S29','리눅스 마스터','2012-11-12');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S31','ITQ','2010-05-17');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S51','네트워크관리사 2급','2010-06-07');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S148','컴퓨터활용능력 2급','2017-02-03');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S180','네트워크관리사 2급','2011-06-25');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S185','ITQ','2016-06-20');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S32','컴퓨터활용능력 2급','2018-06-09');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S77','정보처리산업기사','2012-05-19');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S78','리눅스 마스터','2017-05-05');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S85','ITQ','2019-09-13');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S60','ITQ','2014-11-17');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S82','컴퓨터활용능력 2급','2013-03-01');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S157','정보처리기사','2012-01-05');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S119','컴퓨터활용능력 2급','2019-04-28');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S63','리눅스 마스터','2010-07-31');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S92','리눅스 마스터','2012-09-03');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S177','ITQ','2011-09-12');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S134','정보처리산업기사','2013-08-04');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S112','리눅스 마스터','2016-10-01');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S199','CCNA','2013-06-26');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S17','CCNA','2014-07-22');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S70','정보처리산업기사','2010-05-28');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S129','CCNA','2012-01-05');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S56','정보처리기사','2017-04-01');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S142','정보처리 기능사','2014-08-07');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S158','ITQ','2019-09-24');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S69','CCNA','2015-10-25');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S73','네트워크관리사 2급','2018-04-24');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S198','네트워크관리사 2급','2015-02-04');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S87','네트워크관리사 2급','2016-03-28');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S40','정보처리기사','2018-05-13');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S90','정보처리기사','2015-01-17');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S23','네트워크관리사 2급','2013-12-25');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S53','정보처리 기능사','2012-07-03');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S25','CCNA','2016-02-23');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S17','컴퓨터활용능력 2급','2015-07-15');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S127','정보처리 기능사','2019-11-13');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S175','정보처리산업기사','2014-09-01');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S186','정보처리 기능사','2014-01-10');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S111','정보처리 기능사','2010-06-03');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S158','ITQ','2018-03-14');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S106','정보처리산업기사','2017-11-27');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S173','컴퓨터활용능력 2급','2017-09-26');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S54','정보처리산업기사','2015-08-10');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S174','정보처리기사','2017-07-01');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S189','정보처리기사','2014-03-24');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S30','정보처리산업기사','2013-08-11');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S114','리눅스 마스터','2010-03-02');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S198','CCNA','2015-12-08');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S29','정보처리기사','2011-04-11');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S123','네트워크관리사 2급','2018-03-17');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S43','정보처리산업기사','2016-08-24');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S197','CCNA','2014-10-15');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S118','정보처리기사','2016-07-13');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S173','정보처리 기능사','2012-11-05');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S200','정보처리 기능사','2017-06-29');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S149','정보처리 기능사','2014-07-13');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S21','정보처리기사','2019-07-09');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S171','정보처리기사','2017-11-26');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S178','정보처리기사','2010-06-09');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S160','정보처리산업기사','2018-01-14');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S57','정보처리기사','2018-05-08');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S52','리눅스 마스터','2011-04-05');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S86','컴퓨터활용능력 2급','2019-02-19');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S154','정보처리 기능사','2011-05-01');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S178','정보처리 기능사','2010-12-07');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S12','정보처리산업기사','2011-08-22');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S44','ITQ','2013-07-07');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S155','정보처리기사','2013-11-12');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S103','컴퓨터활용능력 2급','2016-09-03');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S92','정보처리 기능사','2012-07-16');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S162','컴퓨터활용능력 2급','2015-12-30');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S29','정보처리산업기사','2015-02-10');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S79','ITQ','2010-03-31');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S6','컴퓨터활용능력 2급','2011-04-21');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S4','ITQ','2017-01-14');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S134','CCNA','2019-12-19');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S193','CCNA','2010-02-25');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S110','정보처리기사','2012-05-16');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S38','컴퓨터활용능력 2급','2012-06-22');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S8','정보처리 기능사','2011-11-06');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S166','정보처리기사','2018-01-19');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S3','CCNA','2010-05-25');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S120','정보처리 기능사','2014-01-12');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S23','리눅스 마스터','2019-07-04');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S69','정보처리산업기사','2016-06-16');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S106','CCNA','2012-03-27');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S177','정보처리산업기사','2012-03-15');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S116','정보처리 기능사','2012-11-22');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S48','네트워크관리사 2급','2019-06-06');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S121','CCNA','2015-04-29');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S181','정보처리 기능사','2015-06-19');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S148','정보처리산업기사','2013-02-20');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S72','CCNA','2016-09-06');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S114','CCNA','2016-11-12');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S66','CCNA','2019-04-30');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S8','리눅스 마스터','2010-05-29');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S50','ITQ','2019-05-29');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S136','리눅스 마스터','2017-09-03');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S125','정보처리산업기사','2011-01-04');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S86','ITQ','2010-07-30');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S177','정보처리기사','2017-06-06');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S81','컴퓨터활용능력 2급','2016-12-06');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S3','컴퓨터활용능력 2급','2015-05-16');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S24','정보처리기사','2014-07-27');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S52','정보처리 기능사','2016-07-03');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S192','정보처리산업기사','2011-05-07');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S49','정보처리산업기사','2017-01-25');
insert into tblStdLicense(licenseSeq,stdSeq,licenseName,licenseDate) values(seqStdLicense.nextVal,'S146','컴퓨터활용능력 2급','2012-03-22');

commit;
